# app/schemas.py

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, EmailStr, Field


class IncidentCategory(StrEnum):
    """Allowed incident categories returned by the classifier.

    Using an enum prevents the AI response from introducing uncontrolled
    or inconsistent category names.
    """

    VPN = "VPN"
    NETWORK = "Redes"
    ACCESS = "Accesos"
    EMAIL = "Correo"
    HARDWARE = "Hardware"
    OPERATING_SYSTEM = "Sistema Operativo"
    DATABASE = "Base de Datos"
    APPLICATIONS = "Aplicaciones"
    SECURITY = "Seguridad"
    CLOUD = "Cloud"
    OTHER = "Otro"


class IncidentPriority(StrEnum):
    """Allowed priority levels for incident triage."""

    LOW = "Baja"
    MEDIUM = "Media"
    HIGH = "Alta"
    CRITICAL = "Crítica"


class ResponsibleArea(StrEnum):
    """Internal support areas that can own an incident."""

    IT_SUPPORT = "Soporte TI"
    INFRASTRUCTURE = "Infraestructura"
    SECURITY = "Seguridad"
    DATABASE = "Base de Datos"
    APPLICATIONS = "Aplicaciones"
    CLOUD = "Cloud"


class ConfidenceLevel(StrEnum):
    """Qualitative confidence level assigned to the classification.

    This is not a statistical probability. It represents the model's
    estimated confidence using a controlled set of labels.
    """

    LOW = "Baja"
    MEDIUM = "Media"
    HIGH = "Alta"


class SourceChannel(StrEnum):
    """Allowed channels from where an incident can be submitted."""

    WEB = "web"
    POSTMAN = "postman"
    API = "api"


class IncidentRequest(BaseModel):
    """Payload received by the classification endpoint.

    FastAPI uses this schema to validate incoming requests before they
    reach the endpoint logic.
    """

    title: str = Field(
        ...,
        min_length=5,
        max_length=120,
        description="Short title describing the IT incident.",
        examples=["No puedo conectarme a la VPN"],
    )
    description: str = Field(
        ...,
        min_length=15,
        max_length=2000,
        description="Detailed description of the IT incident.",
        examples=[
            "Desde ayer intento conectarme a la VPN de la empresa, pero aparece error de autenticación."
        ],
    )
    reported_by: EmailStr | None = Field(
        default=None,
        description="Optional email of the person reporting the incident.",
        examples=["usuario.demo@empresa.com"],
    )
    source_channel: SourceChannel = Field(
        default=SourceChannel.API,
        description="Channel used to report the incident.",
    )


class IncidentClassification(BaseModel):
    """Structured classification generated by the AI classifier.

    The backend will validate that model outputs match this schema before
    returning or storing the classification.
    """

    category: IncidentCategory
    priority: IncidentPriority
    responsible_area: ResponsibleArea
    summary: str = Field(..., min_length=10, max_length=600)
    suggested_action: str = Field(..., min_length=10, max_length=800)
    confidence_level: ConfidenceLevel
    needs_human_review: bool


class IncidentResponse(IncidentClassification):
    """API response returned after an incident is classified."""

    incident_id: str
    model_name: str
    created_at: datetime


class IncidentHistoryItem(BaseModel):
    """Compact incident record returned by the history listing endpoint."""

    incident_id: str
    title: str
    category: IncidentCategory
    priority: IncidentPriority
    responsible_area: ResponsibleArea
    confidence_level: ConfidenceLevel
    needs_human_review: bool
    model_name: str
    created_at: datetime


class IncidentDetailResponse(BaseModel):
    """Detailed incident record returned by the incident lookup endpoint.

    The raw model response is intentionally not exposed by the public API.
    It remains stored in BigQuery for audit and troubleshooting.
    """

    incident_id: str
    title: str
    description: str
    reported_by: str | None
    source_channel: SourceChannel

    category: IncidentCategory
    priority: IncidentPriority
    responsible_area: ResponsibleArea
    summary: str
    suggested_action: str
    confidence_level: ConfidenceLevel
    needs_human_review: bool

    model_name: str
    model_latency_ms: int
    created_at: datetime


class RuntimeReadinessResponse(BaseModel):
    """Readiness response generated from runtime configuration checks."""

    status: str
    environment: str
    classifier_provider: str
    bigquery_persistence_enabled: bool
    checks: dict[str, str]


class ErrorResponse(BaseModel):
    """Standard error response used by the API."""

    error: str
    message: str